name: my_todo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_slider_drawer: ^2.1.3
  ftoast: ^2.0.0
  hive_flutter: ^1.1.0
  intl: ^0.20.1
  lottie: ^3.2.0
  panara_dialogs: ^0.1.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/
